site_name: Mardi DOIP Server Docs
site_description: Strict DOIP server and client documentation
site_url: https://mardi4nfdi.github.io/mardi_doip_server/
use_directory_urls: true
docs_dir: content
site_dir: site
theme:
  name: shadcn
nav:
  - Home: index.md
  - Server: server.md
  - Client: client.md
  - Client CLI: client_cli.md
  - Docker: docker.md
  - Configuration: configuration.md
  - Development: development.md
  - Project Layout: project_structure.md
