site_name: Mardi DOIP Server Docs
site_description: Strict DOIP server and client documentation
docs_dir: content
site_dir: site
theme:
  name: shadcn
nav:
  - Home: index.md
  - Server: server.md
  - Client: client.md
  - Client CLI: client_cli.md
  - Docker: docker.md
extra:
  disable_next_prev: true